"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, RefreshCw } from "lucide-react";
import { type RiskAnalysisResult } from "@credora/shared";
import { apiFetch } from "../../lib/api";
import { Disclaimer } from "../../components/site-chrome";
import { RiskGauge } from "../../components/risk-gauge";
import { FactorWaterfall } from "../../components/factor-waterfall";
import Link from "next/link";
type Response = RiskAnalysisResult & { id: string };
const fields = [
  ["annualIncome", "Annual income", "85000", 1000], ["creditScore", "Credit score", "720", 300], ["monthlyDebt", "Monthly debt", "900", 0], ["requestedLoanAmount", "Requested loan", "18000", 100], ["loanTermMonths", "Term (months)", "36", 6],
] as const;
export function AnalyzerClient() {
  const [result, setResult] = useState<Response>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(undefined); const values = Object.fromEntries(new FormData(event.currentTarget)); const body = { ...Object.fromEntries(Object.entries(values).map(([key, value]) => [key, key === "loanPurpose" ? value : Number(value)])), loanPurpose: String(values.loanPurpose || "debt consolidation") }; try { setResult(await apiFetch<Response>("/api/risk/analyze", { method: "POST", body: JSON.stringify(body) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to run the simulation."); } finally { setLoading(false); } }
  return <div className="mx-auto max-w-7xl px-5 py-12"><div className="mb-8"><p className="text-sm font-medium text-[#61e6cf]">Risk analyzer</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Model a transparent scenario.</h1><p className="mt-3 max-w-2xl text-[#b8d3cf]">The score is deterministic and versioned. No protected-class attributes are collected or used.</p></div><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={submit} className="glass rounded-3xl p-6"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name, label, value, min]) => <label className="text-sm" key={name}>{label}<input className="input mt-2" type="number" name={name} defaultValue={value} min={min} required /></label>)}<label className="text-sm sm:col-span-2">Loan purpose<select className="input mt-2" name="loanPurpose" defaultValue="debt consolidation"><option>debt consolidation</option><option>home improvement</option><option>education</option><option>major purchase</option></select></label></div><button className="button button-primary mt-6 w-full" disabled={loading}>{loading ? <><RefreshCw className="h-4 w-4 animate-spin" /> Calculating</> : <>Run simulation <ArrowRight className="h-4 w-4" /></>}</button>{error && <p role="alert" className="mt-4 text-sm text-[#f6ad65]">{error}</p>}<div className="mt-6"><Disclaimer compact /></div></form><section className="glass rounded-3xl p-6">{result ? <><div className="flex flex-wrap items-center gap-6"><RiskGauge value={Math.round(result.result.riskScore)} label={result.result.riskBand.replace("_", " ")}/><div><p className="text-sm text-[#9cb7b5]">Simulated approval signal</p><p className="mt-2 text-5xl font-semibold text-[#61e6cf]">{Math.round(result.result.approvalProbability * 100)}%</p><p className="mt-2 text-sm uppercase tracking-[.14em] text-[#f6ad65]">{result.result.simulatedDecision.replaceAll("_", " ")}</p><Link className="mt-4 inline-block text-sm text-[#61e6cf]" href={`/analyzer/results/${result.id}`}>Open full result →</Link></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Risk score", result.result.riskScore], ["Projected DTI", `${(result.derived.dtiAfterLoan * 100).toFixed(1)}%`], ["Estimated APR", `${result.result.suggestedAprMin}–${result.result.suggestedAprMax}%`]].map(([label, value]) => <div className="rounded-xl border border-[#b9eae11c] p-4" key={label as string}><p className="text-xs text-[#9cb7b5]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div><h2 className="mt-7 font-semibold">Factor waterfall</h2><div className="mt-4"><FactorWaterfall factors={[...result.explanation.positiveFactors, ...result.explanation.negativeFactors].map((factor) => ({ label: factor.label, impact: factor.impact }))}/></div></> : <div className="flex min-h-96 items-center justify-center text-center text-[#9cb7b5]"><p>Enter a scenario to see transparent, simulated results here.</p></div>}</section></div></div>;
}
