import Link from "next/link";
import { ArrowUpRight, ChartNoAxesCombined, FileText, ScanSearch, Sparkles } from "lucide-react";
import { Disclaimer } from "../components/site-chrome";
import { RiskGauge } from "../components/risk-gauge";

const capabilities = [[ScanSearch, "Explainable simulation", "See the signals behind every simulated decision."], [ChartNoAxesCombined, "Scenario intelligence", "Compare borrower changes without a black box."], [FileText, "Report studio", "Queue polished educational PDF reports."]];
export default function Home() {
  return <div className="grid-glow"><section className="relative mx-auto max-w-7xl overflow-hidden px-5 pb-16 pt-20 md:pb-28 md:pt-32"><div className="hero-orb absolute right-[-8rem] top-16 h-80 w-80 rounded-full bg-[#61e6cf16] blur-3xl"/><div className="max-w-3xl"><p className="mb-5 flex items-center gap-2 text-sm font-medium text-[#61e6cf]"><Sparkles className="h-4 w-4" /> A calmer way to explore credit risk</p><h1 className="text-5xl font-semibold tracking-[-.05em] text-balance md:text-7xl">Credit intelligence that shows its work.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#b8d3cf]">Credora turns financial inputs into an explainable, deterministic loan simulation—then lets you explore the “what if” without pretending to be a lender.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/demo" className="button button-primary">Explore demo <ArrowUpRight className="h-4 w-4" /></Link><Link href="/analyzer" className="button button-secondary">Run a simulation</Link></div></div><div className="glass relative mt-14 grid gap-5 overflow-hidden rounded-3xl p-6 md:grid-cols-[1.25fr_.75fr]"><div className="scan-line absolute inset-x-0 top-0 h-px bg-[#61e6cf55]"/><div className="flex items-center gap-6"><RiskGauge/><div><p className="text-sm text-[#9cb7b5]">Simulated approval signal</p><p className="mt-2 text-4xl font-semibold text-[#61e6cf]">78%</p><p className="mt-3 text-sm text-[#b8d3cf]">Good simulated risk band · estimated APR 9.4–12.2%</p></div></div><div className="rounded-2xl border border-[#b9eae11c] bg-black/15 p-5"><p className="text-sm font-medium">Why this moved</p><p className="mt-3 text-sm leading-6 text-[#b8d3cf]">Strong score and stable debt-to-income improve the scenario. Everything remains educational, explainable, and reviewable.</p></div></div><div className="mt-8 max-w-3xl"><Disclaimer /></div></section><section className="mx-auto grid max-w-7xl gap-4 px-5 pb-20 md:grid-cols-3">{capabilities.map(([Icon, title, description]) => <article className="glass rounded-2xl p-6" key={title as string}><Icon className="h-5 w-5 text-[#61e6cf]" /><h2 className="mt-8 text-xl font-semibold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-[#9cb7b5]">{description as string}</p></article>)}</section></div>;
}
