"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ListChecks, RefreshCw, Sparkles, Trash2 } from "lucide-react";
import { apiFetch } from "../../lib/api";
import { Disclaimer } from "../../components/site-chrome";

type Analysis = { _id: string; result: { riskScore: number; riskBand: string }; createdAt: string };
type Item = { _id: string; title: string; description: string; priority: "high" | "medium" | "low"; estimatedImpact: number; completed: boolean };
type Plan = { _id: string; title: string; analysisId: string; items: Item[]; updatedAt: string };

export function ImprovementPlansClient() {
  const [plans, setPlans] = useState<Plan[]>([]); const [analyses, setAnalyses] = useState<Analysis[]>([]); const [selectedAnalysis, setSelectedAnalysis] = useState<string>(); const [error, setError] = useState<string>(); const [creating, setCreating] = useState(false);
  const reload = () => Promise.all([apiFetch<{ plans: Plan[] }>("/api/improvement-plans"), apiFetch<{ analyses: Analysis[] }>("/api/risk/analyses")]).then(([planResult, analysisResult]) => { setPlans(planResult.plans); setAnalyses(analysisResult.analyses); setSelectedAnalysis((current) => current ?? analysisResult.analyses[0]?._id); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load improvement plans."));
  useEffect(() => { reload(); }, []);
  async function create() { if (!selectedAnalysis) return; setCreating(true); setError(undefined); try { await apiFetch("/api/improvement-plans/from-autopilot", { method: "POST", body: JSON.stringify({ analysisId: selectedAnalysis }) }); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create an Autopilot plan."); } finally { setCreating(false); } }
  async function toggle(plan: Plan, item: Item) { try { await apiFetch(`/api/improvement-plans/${plan._id}/items/${item._id}`, { method: "PATCH", body: JSON.stringify({ completed: !item.completed }) }); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update plan item."); } }
  async function remove(id: string) { if (!window.confirm("Delete this improvement plan?")) return; try { await apiFetch(`/api/improvement-plans/${id}`, { method: "DELETE" }); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete plan."); } }
  return <div className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-medium text-[#61e6cf]">Improvement plans</p><h1 className="mt-2 text-4xl font-semibold">Turn simulated insights into trackable steps.</h1><p className="mt-3 max-w-2xl text-[#b8d3cf]">Autopilot creates transparent, deterministic what-if steps. Completing an item tracks progress here; it does not change your financial profile or a real credit score.</p><section className="glass mt-7 flex flex-wrap items-center gap-3 rounded-2xl p-5"><ListChecks className="h-5 w-5 text-[#61e6cf]"/><select className="input min-w-64 flex-1" value={selectedAnalysis ?? ""} onChange={(event) => setSelectedAnalysis(event.target.value)} disabled={!analyses.length}><option value="">Select a saved simulation</option>{analyses.map((analysis) => <option key={analysis._id} value={analysis._id}>Risk score {Math.round(analysis.result.riskScore)} · {analysis.result.riskBand.replace("_", " ")}</option>)}</select><button className="button button-primary" onClick={create} disabled={!selectedAnalysis || creating}>{creating ? <><RefreshCw className="h-4 w-4 animate-spin"/>Building plan</> : <><Sparkles className="h-4 w-4"/>Build from Autopilot</>}</button></section>{error && <p role="alert" className="mt-4 text-sm text-[#f6ad65]">{error}</p>}<div className="mt-7 grid gap-5 lg:grid-cols-2">{plans.map((plan) => { const completed = plan.items.filter((item) => item.completed).length; return <article className="glass rounded-3xl p-6" key={plan._id}><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">{plan.title}</h2><p className="mt-2 text-sm text-[#9cb7b5]">{completed}/{plan.items.length} simulated steps complete</p></div><button aria-label={`Delete ${plan.title}`} className="button button-secondary p-2" onClick={() => remove(plan._id)}><Trash2 className="h-4 w-4"/></button></div><div className="mt-5 space-y-3">{plan.items.map((item) => <button className={`flex w-full items-start gap-3 rounded-xl border p-4 text-left transition ${item.completed ? "border-[#61e6cf66] bg-[#61e6cf0a]" : "border-[#b9eae11c]"}`} onClick={() => toggle(plan, item)} key={item._id}><CheckCircle2 className={`mt-0.5 h-5 w-5 shrink-0 ${item.completed ? "text-[#61e6cf]" : "text-[#607a78]"}`}/><span><span className="block font-medium">{item.title}</span><span className="mt-1 block text-sm text-[#9cb7b5]">{item.description}</span><span className="mt-2 block text-xs uppercase tracking-[.12em] text-[#61e6cf]">{item.priority} priority · {item.estimatedImpact >= 0 ? "+" : ""}{item.estimatedImpact} simulated points</span></span></button>)}</div></article>; })}</div>{!plans.length && <div className="glass mt-7 rounded-3xl p-10 text-center text-[#9cb7b5]">Choose a saved result to create your first deterministic improvement plan.</div>}<div className="mt-8"><Disclaimer/></div></div>;
}
