"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Download, FilePlus2, RefreshCw, Trash2 } from "lucide-react";
import { apiFetch } from "../../lib/api";
import { Disclaimer } from "../../components/site-chrome";

type Report = { _id: string; title: string; status: "queued" | "processing" | "completed" | "failed" | "expired" | "deleted"; createdAt: string; error?: { message: string } };
type Analysis = { _id: string; input: { creditScore: number }; result: { riskBand: string; riskScore: number } };

export function ReportsClient() {
  const [reports, setReports] = useState<Report[]>([]); const [analyses, setAnalyses] = useState<Analysis[]>([]); const [analysisId, setAnalysisId] = useState<string>(); const [error, setError] = useState<string>(); const [creating, setCreating] = useState(false);
  const reload = () => Promise.all([apiFetch<{ reports: Report[] }>("/api/reports"), apiFetch<{ analyses: Analysis[] }>("/api/risk/analyses")]).then(([reportResult, analysisResult]) => { setReports(reportResult.reports); setAnalyses(analysisResult.analyses); setAnalysisId((current) => current ?? analysisResult.analyses[0]?._id); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load reports."));
  useEffect(() => { reload(); const timer = window.setInterval(reload, 4000); return () => window.clearInterval(timer); }, []);
  async function create() { if (!analysisId) return; setCreating(true); try { await apiFetch("/api/reports", { method: "POST", body: JSON.stringify({ analysisId, title: "Credora educational simulation report" }) }); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to queue report."); } finally { setCreating(false); } }
  async function remove(id: string) { if (!window.confirm("Delete this report record?")) return; try { await apiFetch(`/api/reports/${id}`, { method: "DELETE" }); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete report."); } }
  return <div className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-medium text-[#61e6cf]">Report Studio</p><h1 className="mt-2 text-4xl font-semibold">Queued reports, visible lifecycle.</h1><p className="mt-4 text-[#b8d3cf]">Build an educational PDF from a saved simulation. It is not a credit report, lending decision, or underwriting document.</p><section className="glass mt-7 flex flex-wrap gap-3 rounded-2xl p-5"><select className="input min-w-64 flex-1" value={analysisId ?? ""} onChange={(event) => setAnalysisId(event.target.value)}><option value="">Select saved simulation</option>{analyses.map((analysis) => <option key={analysis._id} value={analysis._id}>Risk score {Math.round(analysis.result.riskScore)} · {analysis.result.riskBand.replace("_", " ")} · credit {analysis.input.creditScore}</option>)}</select><button className="button button-primary" onClick={create} disabled={!analysisId || creating}>{creating ? <><RefreshCw className="h-4 w-4 animate-spin"/>Queuing report</> : <><FilePlus2 className="h-4 w-4"/>Generate PDF</>}</button></section>{error && <p role="alert" className="mt-4 text-sm text-[#f6ad65]">{error}</p>}<div className="glass mt-7 divide-y divide-[#b9eae11c] rounded-2xl p-2">{reports.map((report) => <article className="flex flex-wrap items-center justify-between gap-4 p-4" key={report._id}><div><Link className="font-medium hover:text-[#61e6cf]" href={`/reports/${report._id}`}>{report.title}</Link><p className="mt-1 text-xs uppercase tracking-[.14em] text-[#9cb7b5]">{report.status}</p><p className="mt-1 text-xs text-[#9cb7b5]">{new Date(report.createdAt).toLocaleString()}</p>{report.error && <p className="mt-2 text-xs text-[#f6ad65]">{report.error.message}</p>}</div><div className="flex gap-2">{report.status === "completed" && <a className="button button-secondary text-sm" href={`/api/reports/${report._id}/download`}><Download className="h-4 w-4"/>Download</a>}<button className="button button-secondary text-sm" onClick={() => remove(report._id)}><Trash2 className="h-4 w-4"/>Delete</button></div></article>)}{!reports.length && <p className="p-8 text-sm text-[#9cb7b5]">Choose a saved simulation to create the first report.</p>}</div><div className="mt-8"><Disclaimer/></div></div>;
}
