"use client";

import { useEffect, useState } from "react";
import { BarChart3, Trash2 } from "lucide-react";
import { apiFetch } from "../../lib/api";
import { Disclaimer } from "../../components/site-chrome";

type Scenario = { _id: string; name: string; resultSnapshot: { result: { approvalProbability: number; riskBand: string; suggestedAprMin: number; suggestedAprMax: number }; derived: { estimatedMonthlyPayment: number } } };
type ComparedScenario = { id: string; name: string; result: Scenario["resultSnapshot"]["result"]; derived: Scenario["resultSnapshot"]["derived"] };

export function ScenariosClient() {
  const [scenarios, setScenarios] = useState<Scenario[]>([]); const [selected, setSelected] = useState<string[]>([]); const [comparison, setComparison] = useState<ComparedScenario[]>(); const [error, setError] = useState<string>();
  const reload = () => apiFetch<{ scenarios: Scenario[] }>("/api/scenarios").then(({ scenarios }) => { setScenarios(scenarios); setSelected((ids) => ids.filter((id) => scenarios.some((scenario) => scenario._id === id))); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load scenarios."));
  useEffect(() => { reload(); }, []);
  async function compare() { try { setComparison((await apiFetch<{ scenarios: ComparedScenario[] }>("/api/scenarios/compare", { method: "POST", body: JSON.stringify({ ids: selected }) })).scenarios); } catch (cause) { setError(cause instanceof Error ? cause.message : "Select two saved scenarios to compare."); } }
  async function remove(id: string) { if (!window.confirm("Delete this scenario?")) return; try { await apiFetch(`/api/scenarios/${id}`, { method: "DELETE" }); setComparison(undefined); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete scenario."); } }
  return <div className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-medium text-[#61e6cf]">Scenario Lab</p><h1 className="mt-2 text-4xl font-semibold">Compare the change, not just the score.</h1><p className="mt-4 text-[#b8d3cf]">Save a result as a scenario, choose up to five, and compare the same deterministic model inputs side by side.</p>{error && <p role="alert" className="mt-4 text-sm text-[#f6ad65]">{error}</p>}<div className="mt-7 grid gap-4 md:grid-cols-2">{scenarios.map((scenario) => <article className={`glass rounded-2xl p-5 transition ${selected.includes(scenario._id) ? "ring-1 ring-[#61e6cf]" : ""}`} key={scenario._id}><div className="flex justify-between gap-3"><button className="min-w-0 flex-1 text-left" onClick={() => setSelected((ids) => ids.includes(scenario._id) ? ids.filter((id) => id !== scenario._id) : ids.length < 5 ? [...ids, scenario._id] : ids)}><p className="font-semibold">{scenario.name}</p><p className="mt-3 text-sm text-[#b8d3cf]">{Math.round(scenario.resultSnapshot.result.approvalProbability * 100)}% signal · {scenario.resultSnapshot.result.riskBand.replace("_", " ")}</p><p className="mt-2 text-xs text-[#9cb7b5]">APR {scenario.resultSnapshot.result.suggestedAprMin}–{scenario.resultSnapshot.result.suggestedAprMax}% · ${scenario.resultSnapshot.derived.estimatedMonthlyPayment.toFixed(0)}/mo</p></button><button aria-label={`Delete ${scenario.name}`} className="button button-secondary h-9 w-9 p-2" onClick={() => remove(scenario._id)}><Trash2 className="h-4 w-4"/></button></div></article>)}{!scenarios.length && <p className="col-span-full rounded-2xl border border-dashed border-[#b9eae11c] p-8 text-center text-sm text-[#9cb7b5]">Save a scenario from any result page to compare it here.</p>}</div><button onClick={compare} disabled={selected.length < 2} className="button button-primary mt-6"><BarChart3 className="h-4 w-4"/>Compare selected ({selected.length})</button>{comparison && <section className="glass mt-6 overflow-x-auto rounded-3xl p-6"><h2 className="font-semibold">Animated comparison readout</h2><div className="mt-5 min-w-[560px] space-y-5">{comparison.map((scenario) => <div key={scenario.id}><div className="flex justify-between gap-4 text-sm"><span>{scenario.name}</span><span className="text-[#61e6cf]">{Math.round(scenario.result.approvalProbability * 100)}% simulated signal</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#9da8ff] to-[#61e6cf] transition-all duration-700" style={{ width: `${Math.round(scenario.result.approvalProbability * 100)}%` }}/></div><div className="mt-2 grid grid-cols-3 text-xs text-[#9cb7b5]"><span>APR {scenario.result.suggestedAprMin}–{scenario.result.suggestedAprMax}%</span><span>Payment ${scenario.derived.estimatedMonthlyPayment.toFixed(0)}</span><span>{scenario.result.riskBand.replace("_", " ")}</span></div></div>)}</div></section>}<div className="mt-8"><Disclaimer/></div></div>;
}
